name: Example output


on:
  push:
    branches:
      - main
      - master
      - dispatch

jobs:
  bookdown-prod:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    container: inseefrlab/utilitr:latest
    steps:
      - name: Checkout Repository
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          Rscript -e "install.packages(c('remotes'))"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Install package
        run: |
          Rscript -e "devtools::document(roclets = c('rd', 'collate', 'namespace'))"
          Rscript -e "devtools::install()"
      - name: Render Book
        run: |
          Rscript -e "rmarkdown::draft('index.Rmd', template='utilitr', package='utilitr', edit = FALSE)"
          Rscript -e "bookdown::render_book('index.Rmd', output_dir = '_public', output_format = 'utilitr::html_document')"
      - uses: actions/upload-artifact@v2
        with:
          name: _public
          path: _public/
          retention-days: 5
  pagedown:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    container: inseefrlab/utilitr:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Dependencies
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        run: |
          Rscript -e "install.packages(c('remotes'))"
          Rscript -e "remotes::install_github('rstudio/pagedown')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Install package
        run: |
          Rscript -e "devtools::document(roclets = c('rd', 'collate', 'namespace'))"
          Rscript -e "devtools::install()"
      - name: Render Book
        run: |
          Rscript -e "rmarkdown::draft('index.Rmd', template='utilitr', package='utilitr', edit = FALSE)"
          mkdir _pagedown_output -p
          Rscript -e "utilitr::pdf_document()"
      - name: Trigger a build in utilitr doc
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/inseefrlab/utilitr/dispatches --data '{"event_type": "update-template"}'
      - uses: actions/upload-artifact@v2
        with:
          name: DocumentationR_pagedown
          path: _pagedown_output/DocumentationR.pdf
          retention-days: 5


